### ISSUE TITLE
PUL00 | Inception

### ISSUE THREAD

**Issue by glixius** [glixius/pulsar-client#1]
### Tasks

- [x]  Create Angular workspace
- [x] Create initial project structure.
- [x] Add initial routing.
- [x] Add auth library.
- [x] Add analytics in monitoring library.
- [x] Add logging in monitoring library.
- [ ] Add API in data library.
- [ ] Add LocalStorage in data library.
- [x] Add state management.
