### ISSUE TITLE
PUL01 | Layout

### ISSUE THREAD

**Issue by glixius** [glixius/pulsar-client#2]
### Tasks

- [ ] Add loading component.
- [ ] Add header component.
- [ ] Add notification component.
- [ ] Create notification library.
