### ISSUE TITLE
PUL02 | Identify user

### ISSUE THREAD

**Issue by glixius** [glixius/pulsar-client#3]
### Tasks

- [ ] Create SessionService
- [ ] Create UserService
- [ ] Add LocalStorage to data library.
- [ ] Create authentication view.
- [ ] Create unauthorized view.
- [ ] Create AuthGuard.
- [ ] Save session and user.
