### ISSUE TITLE
PUL03 | Display band

### ISSUE THREAD

**Issue by glixius** [glixius/pulsar-client#4]
### Tasks

- [ ] Create band profile component.
- [ ] Create band service.
- [ ] Add empty and error messages.
- [ ] Implement role specific presentation.
- [ ] Implement role aware behavior.
